### ISSUE TITLE
icons big annoying

### ISSUE THREAD

**Issue by Bowser65** [AlexFlipnote/homepage#10]
yes this time it's the good place (i think)

![8vjzdbx6](https://user-images.githubusercontent.com/9999055/42741557-b6ad283e-88b3-11e8-9f78-fbd932632c9f.png)

**Comment by AlexFlipnote** [comment]
Oh, that's an easy fix, I just need to force width/height on the placement and it should go fine (72x72)
Will push an update for it asap

**Comment by AlexFlipnote** [comment]
Fixed
