### ISSUE TITLE
https://alexflipnote.xyz/homepage doesn't work

### ISSUE THREAD

**Issue by TheOnlyWayUp** [AlexFlipnote/homepage#25]
https://alexflipnote.xyz/homepage redirects to http://ww16.alexflipnote.xyz/homepage and doesn't contain anything regarding this repository.

**Comment by AlexFlipnote** [comment]
I do not own the `.xyz` anymore, I moved to `.dev` (haha yes, dev cause developer)

https://alexflipnote.dev/homepage/
